#!/bin/sh
echo  "Can't  commit that dum  dum  dum doo, doo doo doo dooo"
# $(python test.py)
files=$(git diff --name-only --cached)
output=$(python guardian-script.py $files)
if [ "$output" != "" ]; then
   lines=$(echo $output | tr ";" "\n")

    for line in $lines
    do
        echo "$line"
    done
   exit 1
else
   echo "all good  mate"
fi
