#!/bin/sh
echo  "Searching for possible sensitive data"
# $(python test.py)
files=$(git diff --name-only --cached)
output=$(python guardian-script.py $files)
if [ "$output" != "" ]; then
  while IFS=';' read -ra ADDR; do
      echo $ADDR
  done <<< "$output"
   exit 1
fi
